/**
 * @module tests/pii
 * @description Playwright test for default-on PII/environment anonymization.
 *
 * Loads the deliberately PII-heavy `scc_test-pii.tar.xz` fixture (generated by
 * `create-fixtures.sh`, never committed as a binary) and asserts that the web
 * pipeline scrubs every sensitive value **by default** — no flag, no opt-in.
 *
 * Verifies:
 *   - Raw IPs, MACs, email, secret, subscription GUID, and FQDN hostnames do
 *     NOT appear anywhere in the rendered output.
 *   - IPs are replaced with subnet-preserving tokens (`[[IPv4|net-X|hN]]`), and
 *     MAC tokens keep the vendor OUI (`[[MAC|00:0d:3a|devN]]`).
 *   - Subnet correlation survives: the two same-/24 addresses map to one net
 *     label; the third subnet maps to a different label.
 *   - Loopback (`127.0.0.1`) is diagnostic, not PII, and is preserved verbatim.
 */
import { test, expect } from './coverage-fixture.js';
import { uploadAndWaitForAnalysis, navigateToApp } from './test-helpers.js';

test.describe('PII anonymization (default-on)', () => {

  test.beforeEach(async ({ page }, testInfo) => {
    await navigateToApp(page, testInfo);
    await expect(page.locator('h1')).toContainText('RCA Tool');
  });

  test('scrubs all PII from the rendered analysis by default', async ({ page }) => {
    const html = await uploadAndWaitForAnalysis(page, 'scc_test-pii.tar.xz');

    // The PII-bearing Network Interfaces section renders.
    expect(html).toContain('Network Interfaces');

    // 1. No raw PII survives anywhere in the rendered output.
    const rawPii = [
      '10.20.30.40', '10.20.30.41', '172.16.99.5',
      '00:0d:3a:aa:bb:cc', '00:0d:3a:aa:bb:cd', '00:0d:3a:dd:ee:ff',
      'jdoe@contoso.example.com', 'S3cr3tP@ssw0rd',
      '11111111-2222-3333-4444-555555555555',
      'db01.corp.contoso.example.com',
    ];
    for (const raw of rawPii) {
      expect(html, `raw PII must be scrubbed: ${raw}`).not.toContain(raw);
    }

    // 2. IPs become subnet-preserving tokens; MAC keeps the vendor OUI.
    expect(html).toMatch(/\[\[IPv4\|net-[A-Z]+\|h\d+\]\]/);
    expect(html).toContain('[[MAC|00:0d:3a|');

    // 3. Subnet correlation preserved: at least two distinct subnet labels, and
    //    at least one subnet contains two distinct hosts (the same-/24 pair).
    //    (Loopback-preservation is covered by the crate's unit tests; the UI
    //    does not render the loopback interface, so it is not asserted here.)
    const byNet = {};
    for (const m of html.matchAll(/\[\[IPv4\|net-([A-Z]+)\|h(\d+)\]\]/g)) {
      (byNet[m[1]] ||= new Set()).add(m[2]);
    }
    const groupSizes = Object.values(byNet).map((s) => s.size);
    expect(Object.keys(byNet).length).toBeGreaterThanOrEqual(2);
    expect(Math.max(...groupSizes)).toBeGreaterThanOrEqual(2);
  });
});
